
# Workspace
export PATH+=":$HOME/workspace/bin"

# Brew
export HOMEBREW_GITHUB_API_TOKEN="empty"

# MacPorts
#export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
 
# Android
#export PATH+=":$HOME/workspace/sdk/android-sdk-macosx/tools"
#export PATH+=":$HOME/workspace/sdk/android-sdk-macosx/platform-tools"
#export PATH+=":$HOME/workspace/sdk/android-ndk-r11c"
#export PATH+=":$HOME/Library/Android/sdk/platform-tools"
#export PATH+=":$HOME/Library/Android/ndk"

#export LANG="ru_RU.UTF-8"
#export LC_ALL="ru_RU.UTF-8"

# Qt (brew)
#export CMAKE_PREFIX_PATH+=":/usr/local/Cellar/qt5/5.6.1-1/lib/cmake/"
